"""Telegraf configuration renderer.

Translates structured monitoring definitions into compliant, valid Telegraf TOML
fragments aligned with Broadcom VCF Operations 9.1 recommendations.
"""

from __future__ import annotations

import json
from typing import List, Optional

from vcf_ops_telegraf_helper.models.monitoring import MonitoringConfig


def _escape_toml_str(val: str) -> str:
    """Format a string safely for TOML, properly escaping backslashes and quotes."""
    return json.dumps(val)


MANAGED_HEADER = """# ------------------------------------------------------------------------------
# Managed by VCF Operations Open Telegraf Helper
# Do not edit this file directly. Changes will be overwritten during updates.
# ------------------------------------------------------------------------------
"""


class TelegrafRenderer:
    """Renders structured monitoring choices into Telegraf TOML configurations."""

    @staticmethod
    def render_system_inputs(config: MonitoringConfig) -> str:
        """Render standard OS monitoring inputs (CPU, memory, disk, network, system).

        Conforms strictly to Broadcom VCF Operations recommendations for Linux OS metrics:
        - CPU requires percpu, totalcpu, collect_cpu_time, report_active.
        - Mem is enabled with default options.
        - Disk supports mount point filters and standard filesystem ignores.
        - Net collects interface stats.
        - System and swap collect standard system health.

        Returns:
            Formatted TOML string ready for placement in telegraf.d/vcf-helper-system.conf.
        """
        lines: List[str] = [MANAGED_HEADER]

        # CPU Input
        if config.cpu.enabled:
            lines.extend([
                "# Read metrics about CPU usage",
                "[[inputs.cpu]]",
                f"  percpu = {str(config.cpu.percpu).lower()}",
                f"  totalcpu = {str(config.cpu.totalcpu).lower()}",
                f"  collect_cpu_time = {str(config.cpu.collect_cpu_time).lower()}",
                f"  report_active = {str(config.cpu.report_active).lower()}",
                "",
            ])

        # Memory Input
        if config.mem.enabled:
            lines.extend([
                "# Read metrics about memory usage",
                "[[inputs.mem]]",
                "",
            ])

        # Disk Input
        if config.disk.enabled:
            lines.extend([
                "# Read metrics about disk usage by mount point",
                "[[inputs.disk]]",
            ])
            if config.disk.mount_points:
                formatted_mps = ", ".join(f'"{mp}"' for mp in config.disk.mount_points)
                lines.append(f"  mount_points = [{formatted_mps}]")
            if config.disk.ignore_fs:
                formatted_ifs = ", ".join(f'"{ifs}"' for ifs in config.disk.ignore_fs)
                lines.append(f"  ignore_fs = [{formatted_ifs}]")
            lines.append("")

        # Network Input
        if config.net.enabled:
            lines.extend([
                "# Read metrics about network interface usage",
                "[[inputs.net]]",
            ])
            if config.net.interfaces:
                formatted_ifs = ", ".join(f'"{i}"' for i in config.net.interfaces)
                lines.append(f"  interfaces = [{formatted_ifs}]")
            lines.append("")

        # System Input
        if config.system.enabled:
            lines.extend([
                "# Read metrics about system load & uptime",
                "[[inputs.system]]",
                "",
            ])

        # Swap Input
        if config.swap.enabled:
            lines.extend([
                "# Read metrics about swap memory usage",
                "[[inputs.swap]]",
                "",
            ])

        # Disk I/O Input
        if config.diskio.enabled:
            lines.extend([
                "# Read metrics about disk IO by device",
                "[[inputs.diskio]]",
            ])
            if config.diskio.devices:
                devs = ", ".join(f'"{d}"' for d in config.diskio.devices)
                lines.append(f"  devices = [{devs}]")
            lines.append("")

        # Processes Input
        if config.processes.enabled:
            lines.extend([
                "# Get the number of processes and group them by status",
                "[[inputs.processes]]",
                "",
            ])

        # Windows Performance Counters
        if config.win_perf_counters.enabled:
            lines.extend([
                "# Read Windows Performance Counters",
                "[[inputs.win_perf_counters]]",
                "  [[inputs.win_perf_counters.object]]",
                '    ObjectName = "Processor"',
                '    Instances = ["*"]',
                '    Counters = ["% Processor Time", "% Idle Time", "% Privileged Time", "% User Time"]',
                '    Measurement = "win_cpu"',
                "",
                "  [[inputs.win_perf_counters.object]]",
                '    ObjectName = "Memory"',
                '    Instances = ["------"]',
                '    Counters = ["Available Bytes", "Committed Bytes", "% Committed Bytes In Use"]',
                '    Measurement = "win_mem"',
                "",
                "  [[inputs.win_perf_counters.object]]",
                '    ObjectName = "LogicalDisk"',
                '    Instances = ["*"]',
                '    Counters = ["% Free Space", "Free Megabytes", "Current Disk Queue Length"]',
                '    Measurement = "win_disk"',
                "",
                "  [[inputs.win_perf_counters.object]]",
                '    ObjectName = "Network Interface"',
                '    Instances = ["*"]',
                '    Counters = ["Bytes Received/sec", "Bytes Sent/sec", "Packets Received Errors", "Packets Outbound Errors"]',
                '    Measurement = "win_net"',
                "",
                "  [[inputs.win_perf_counters.object]]",
                '    ObjectName = "System"',
                '    Instances = ["------"]',
                '    Counters = ["Context Switches/sec", "System Calls/sec", "Processor Queue Length", "System Up Time"]',
                '    Measurement = "win_system"',
                "",
            ])

        # Windows Services
        if config.win_services.enabled:
            lines.extend([
                "# Read Windows service states",
                "[[inputs.win_services]]",
            ])
            svc_list = ", ".join(_escape_toml_str(s) for s in config.win_services.service_names)
            lines.append(f"  service_names = [{svc_list}]")
            lines.append("")

        # NGINX
        if config.nginx.enabled:
            lines.extend([
                "# Read NGINX status metrics",
                "[[inputs.nginx]]",
            ])
            urls = ", ".join(_escape_toml_str(u) for u in config.nginx.urls)
            lines.append(f"  urls = [{urls}]")
            lines.append("")

        # Apache
        if config.apache.enabled:
            lines.extend([
                "# Read Apache server-status metrics",
                "[[inputs.apache]]",
            ])
            urls = ", ".join(_escape_toml_str(u) for u in config.apache.urls)
            lines.append(f"  urls = [{urls}]")
            lines.append("")

        # MySQL
        if config.mysql.enabled:
            lines.extend([
                "# Read MySQL / MariaDB server metrics",
                "[[inputs.mysql]]",
            ])
            servers = ", ".join(_escape_toml_str(s) for s in config.mysql.servers)
            lines.append(f"  servers = [{servers}]")
            lines.append("")

        # PostgreSQL
        if config.postgresql.enabled:
            lines.extend([
                "# Read PostgreSQL server metrics",
                "[[inputs.postgresql]]",
                f"  address = {_escape_toml_str(config.postgresql.address)}",
                "",
            ])

        # Microsoft SQL Server
        if config.mssql.enabled:
            lines.extend([
                "# Read Microsoft SQL Server metrics",
                "[[inputs.sqlserver]]",
            ])
            servers = ", ".join(_escape_toml_str(s) for s in config.mssql.servers)
            lines.append(f"  servers = [{servers}]")
            lines.append("")

        # Docker
        if config.docker.enabled:
            lines.extend([
                "# Read Docker container metrics",
                "[[inputs.docker]]",
                f"  endpoint = {_escape_toml_str(config.docker.endpoint)}",
                "",
            ])

        # Ping
        if config.ping.enabled:
            lines.extend([
                "# Read ping and reachability metrics",
                "[[inputs.ping]]",
            ])
            urls = ", ".join(_escape_toml_str(u) for u in config.ping.urls)
            lines.append(f"  urls = [{urls}]")
            lines.append(f"  count = {config.ping.count}")
            lines.append("")

        # Custom TOML Fragment
        if config.custom_toml and config.custom_toml.strip():
            lines.extend([
                "# Custom administrator TOML fragment",
                config.custom_toml.strip(),
                "",
            ])

        return "\n".join(lines).strip() + "\n"

    @staticmethod
    def render_vcf_output(
        collector_address: str,
        hostname: str,
        uuid: str = "",
        ip: str = "",
        verify_ssl: bool = True,
        ca_cert_path: str = "/etc/telegraf/telegraf.d/ca.pem",
        cert_path: str = "/etc/telegraf/telegraf.d/cert.pem",
        key_path: str = "/etc/telegraf/telegraf.d/key.pem",
        vm_mor: Optional[str] = None,
        vc_id: Optional[str] = None,
    ) -> str:
        """Render the Broadcom VCF Operations Cloud Proxy Wavefront HTTP output.

        Conforms to Broadcom VCF Operations 9.1 open-source Telegraf sample configuration.
        Places output in telegraf.d/cloudproxy-http.conf.

        Args:
            collector_address: IP or FQDN of the Cloud Proxy.
            hostname: Target hostname.
            uuid: Host or VM UUID for unmanaged mapping.
            ip: Target IP address.
            verify_ssl: True if SSL certificate verification is enabled.
            ca_cert_path: Path to CA certificate bundle.
            cert_path: Path to client certificate.
            key_path: Path to client private key.
            vm_mor: Optional vCenter VM MOR if managed.
            vc_id: Optional vCenter Instance ID if managed.

        Returns:
            Formatted TOML string for telegraf.d/cloudproxy-http.conf.
        """
        lines: List[str] = [
            MANAGED_HEADER,
            "# Global agent configuration for VCF Operations ingestion",
            "[agent]",
            '  interval = "300s"',
            "  round_interval = true",
            "  metric_batch_size = 1000",
            "  metric_buffer_limit = 2000",
            '  collection_jitter = "0s"',
            '  flush_interval = "60s"',
            '  flush_jitter = "0s"',
            '  precision = ""',
            "  debug = false",
            "  quiet = false",
            '  logfile = ""',
            f'  hostname = "{hostname}"',
            "  omit_hostname = false",
            "",
            "# Output configuration for VCF Operations Cloud Proxy",
            "[[outputs.http]]",
            f'  url = "https://{collector_address}/opensource/default/metric"',
            '  timeout = "5s"',
            '  method = "POST"',
            f"  insecure_skip_verify = {str(not verify_ssl).lower()}",
        ]

        if verify_ssl:
            lines.extend([
                f"  tls_ca = {_escape_toml_str(ca_cert_path)}",
                f"  tls_cert = {_escape_toml_str(cert_path)}",
                f"  tls_key = {_escape_toml_str(key_path)}",
                '  tls_min_version = "TLS13"',
            ])

        lines.extend([
            '  data_format = "wavefront"',
            "",
            "  [outputs.http.headers]",
            '    Content-Type = "text/plain; charset=utf-8"',
        ])

        if vm_mor and vc_id:
            lines.extend([
                f"    vmId = {_escape_toml_str(vm_mor)}",
                f"    vcid = {_escape_toml_str(vc_id)}",
                f"    hostname = {_escape_toml_str(hostname)}",
                '    uuid = ""',
            ])
        else:
            lines.extend([
                f"    uuid = {_escape_toml_str(uuid)}",
                f"    ip = {_escape_toml_str(ip)}",
                f"    hostname = {_escape_toml_str(hostname)}",
            ])

        lines.append("")
        return "\n".join(lines).strip() + "\n"
