"""Telegraf configuration renderer.

Translates structured monitoring definitions into compliant, valid Telegraf TOML
fragments aligned with Broadcom VCF Operations 9.1 recommendations.
"""

from __future__ import annotations

from typing import List, Optional

from vcf_ops_telegraf_helper.models.monitoring import MonitoringConfig


MANAGED_HEADER = """# ------------------------------------------------------------------------------
# Managed by VCF Operations Open Telegraf Helper
# Do not edit this file directly. Changes will be overwritten during updates.
# ------------------------------------------------------------------------------
"""


class TelegrafRenderer:
    """Renders structured monitoring choices into Telegraf TOML configurations."""

    @staticmethod
    def render_system_inputs(config: MonitoringConfig) -> str:
        """Render standard OS monitoring inputs (CPU, memory, disk, network, system).

        Conforms strictly to Broadcom VCF Operations recommendations for Linux OS metrics:
        - CPU requires percpu, totalcpu, collect_cpu_time, report_active.
        - Mem is enabled with default options.
        - Disk supports mount point filters and standard filesystem ignores.
        - Net collects interface stats.
        - System and swap collect standard system health.

        Returns:
            Formatted TOML string ready for placement in telegraf.d/vcf-helper-system.conf.
        """
        lines: List[str] = [MANAGED_HEADER]

        # CPU Input
        if config.cpu.enabled:
            lines.extend([
                "# Read metrics about CPU usage",
                "[[inputs.cpu]]",
                f"  percpu = {str(config.cpu.percpu).lower()}",
                f"  totalcpu = {str(config.cpu.totalcpu).lower()}",
                f"  collect_cpu_time = {str(config.cpu.collect_cpu_time).lower()}",
                f"  report_active = {str(config.cpu.report_active).lower()}",
                "",
            ])

        # Memory Input
        if config.mem.enabled:
            lines.extend([
                "# Read metrics about memory usage",
                "[[inputs.mem]]",
                "",
            ])

        # Disk Input
        if config.disk.enabled:
            lines.extend([
                "# Read metrics about disk usage by mount point",
                "[[inputs.disk]]",
            ])
            if config.disk.mount_points:
                formatted_mps = ", ".join(f'"{mp}"' for mp in config.disk.mount_points)
                lines.append(f"  mount_points = [{formatted_mps}]")
            if config.disk.ignore_fs:
                formatted_ifs = ", ".join(f'"{ifs}"' for ifs in config.disk.ignore_fs)
                lines.append(f"  ignore_fs = [{formatted_ifs}]")
            lines.append("")

        # Network Input
        if config.net.enabled:
            lines.extend([
                "# Read metrics about network interface usage",
                "[[inputs.net]]",
            ])
            if config.net.interfaces:
                formatted_ifs = ", ".join(f'"{i}"' for i in config.net.interfaces)
                lines.append(f"  interfaces = [{formatted_ifs}]")
            lines.append("")

        # System Input
        if config.system.enabled:
            lines.extend([
                "# Read metrics about system load & uptime",
                "[[inputs.system]]",
                "",
            ])

        # Swap Input
        if config.swap.enabled:
            lines.extend([
                "# Read metrics about swap memory usage",
                "[[inputs.swap]]",
                "",
            ])

        # Disk I/O Input
        if config.diskio.enabled:
            lines.extend([
                "# Read metrics about disk IO by device",
                "[[inputs.diskio]]",
            ])
            if config.diskio.devices:
                devs = ", ".join(f'"{d}"' for d in config.diskio.devices)
                lines.append(f"  devices = [{devs}]")
            lines.append("")

        # Processes Input
        if config.processes.enabled:
            lines.extend([
                "# Get the number of processes and group them by status",
                "[[inputs.processes]]",
                "",
            ])

        return "\n".join(lines).strip() + "\n"

    @staticmethod
    def render_vcf_output(
        collector_address: str,
        hostname: str,
        uuid: str = "",
        ip: str = "",
        verify_ssl: bool = True,
        ca_cert_path: str = "/etc/telegraf/telegraf.d/ca.pem",
        cert_path: str = "/etc/telegraf/telegraf.d/cert.pem",
        key_path: str = "/etc/telegraf/telegraf.d/key.pem",
        vm_mor: Optional[str] = None,
        vc_id: Optional[str] = None,
    ) -> str:
        """Render the Broadcom VCF Operations Cloud Proxy Wavefront HTTP output.

        Conforms to Broadcom VCF Operations 9.1 open-source Telegraf sample configuration.
        Places output in telegraf.d/cloudproxy-http.conf.

        Args:
            collector_address: IP or FQDN of the Cloud Proxy.
            hostname: Target hostname.
            uuid: Host or VM UUID for unmanaged mapping.
            ip: Target IP address.
            verify_ssl: True if SSL certificate verification is enabled.
            ca_cert_path: Path to CA certificate bundle.
            cert_path: Path to client certificate.
            key_path: Path to client private key.
            vm_mor: Optional vCenter VM MOR if managed.
            vc_id: Optional vCenter Instance ID if managed.

        Returns:
            Formatted TOML string for telegraf.d/cloudproxy-http.conf.
        """
        lines: List[str] = [
            MANAGED_HEADER,
            "# Global agent configuration for VCF Operations ingestion",
            "[agent]",
            '  interval = "300s"',
            "  round_interval = true",
            "  metric_batch_size = 1000",
            "  metric_buffer_limit = 2000",
            '  collection_jitter = "0s"',
            '  flush_interval = "60s"',
            '  flush_jitter = "0s"',
            '  precision = ""',
            "  debug = false",
            "  quiet = false",
            '  logfile = ""',
            f'  hostname = "{hostname}"',
            "  omit_hostname = false",
            "",
            "# Output configuration for VCF Operations Cloud Proxy",
            "[[outputs.http]]",
            f'  url = "https://{collector_address}/opensource/default/metric"',
            '  timeout = "5s"',
            '  method = "POST"',
            f"  insecure_skip_verify = {str(not verify_ssl).lower()}",
        ]

        if verify_ssl:
            lines.extend([
                f'  tls_ca = "{ca_cert_path}"',
                f'  tls_cert = "{cert_path}"',
                f'  tls_key = "{key_path}"',
                '  tls_min_version = "TLS13"',
            ])

        lines.extend([
            '  data_format = "wavefront"',
            "",
            "  [outputs.http.headers]",
            '    Content-Type = "text/plain; charset=utf-8"',
        ])

        if vm_mor and vc_id:
            lines.extend([
                f'    vmId = "{vm_mor}"',
                f'    vcid = "{vc_id}"',
                f'    hostname = "{hostname}"',
                '    uuid = ""',
            ])
        else:
            lines.extend([
                f'    uuid = "{uuid}"',
                f'    ip = "{ip}"',
                f'    hostname = "{hostname}"',
            ])

        lines.append("")
        return "\n".join(lines).strip() + "\n"
