"""Telegraf configuration renderer.

Translates structured monitoring definitions into compliant, valid Telegraf TOML
fragments aligned with Broadcom VCF Operations 9.1 recommendations.
"""

from __future__ import annotations

import ipaddress
import json
import sys

if sys.version_info >= (3, 11):
    import tomllib
else:
    import tomli as tomllib
from typing import Any, List, Optional

from vcf_ops_telegraf_helper.models.monitoring import MonitoringConfig


def _escape_toml_str(val: Any) -> str:
    """Format a value safely for TOML, properly escaping backslashes and quotes."""
    if val is None:
        return '""'
    return json.dumps(str(val))


MANAGED_HEADER = """# ------------------------------------------------------------------------------
# Managed by VCF Operations Open Telegraf Helper
# Do not edit this file directly. Changes will be overwritten during updates.
# ------------------------------------------------------------------------------
"""


class TelegrafRenderer:
    """Renders structured monitoring choices into Telegraf TOML configurations."""

    @staticmethod
    def render_system_inputs(config: MonitoringConfig) -> str:
        """Render standard OS monitoring inputs (CPU, memory, disk, network, system).

        Conforms strictly to Broadcom VCF Operations recommendations for Linux OS metrics:
        - CPU requires percpu, totalcpu, collect_cpu_time, report_active.
        - Mem is enabled with default options.
        - Disk supports mount point filters and standard filesystem ignores.
        - Net collects interface stats.
        - System and swap collect standard system health.

        Returns:
            Formatted TOML string ready for placement in telegraf.d/vcf-helper-system.conf.
        """
        lines: List[str] = [MANAGED_HEADER]

        # CPU Input
        if config.cpu.enabled:
            lines.extend([
                "# Read metrics about CPU usage",
                "[[inputs.cpu]]",
                f"  percpu = {str(config.cpu.percpu).lower()}",
                f"  totalcpu = {str(config.cpu.totalcpu).lower()}",
                f"  collect_cpu_time = {str(config.cpu.collect_cpu_time).lower()}",
                f"  report_active = {str(config.cpu.report_active).lower()}",
                "",
            ])

        # Memory Input
        if config.mem.enabled:
            lines.extend([
                "# Read metrics about memory usage",
                "[[inputs.mem]]",
                "",
            ])

        # Disk Input
        if config.disk.enabled:
            lines.extend([
                "# Read metrics about disk usage by mount point",
                "[[inputs.disk]]",
            ])
            if config.disk.mount_points:
                formatted_mps = ", ".join(f'"{mp}"' for mp in config.disk.mount_points)
                lines.append(f"  mount_points = [{formatted_mps}]")
            if config.disk.ignore_fs:
                formatted_ifs = ", ".join(f'"{ifs}"' for ifs in config.disk.ignore_fs)
                lines.append(f"  ignore_fs = [{formatted_ifs}]")
            lines.append("")

        # Network Input
        if config.net.enabled:
            lines.extend([
                "# Read metrics about network interface usage",
                "[[inputs.net]]",
            ])
            if config.net.interfaces:
                formatted_ifs = ", ".join(f'"{i}"' for i in config.net.interfaces)
                lines.append(f"  interfaces = [{formatted_ifs}]")
            lines.append("")

        # System Input
        if config.system.enabled:
            lines.extend([
                "# Read metrics about system load & uptime",
                "[[inputs.system]]",
                "",
            ])

        # Swap Input
        if config.swap.enabled:
            lines.extend([
                "# Read metrics about swap memory usage",
                "[[inputs.swap]]",
                "",
            ])

        # Disk I/O Input
        if config.diskio.enabled:
            lines.extend([
                "# Read metrics about disk IO by device",
                "[[inputs.diskio]]",
            ])
            if config.diskio.devices:
                devs = ", ".join(f'"{d}"' for d in config.diskio.devices)
                lines.append(f"  devices = [{devs}]")
            lines.append("")

        # Processes Input
        if config.processes.enabled:
            lines.extend([
                "# Get the number of processes and group them by status",
                "[[inputs.processes]]",
                "",
            ])

        # Windows Performance Counters
        if config.win_perf_counters.enabled:
            perf_start = len(lines)
            proc_insts = config.win_perf_counters.process_instances or ["_Total", "telegraf"]
            proc_insts_formatted = ", ".join(_escape_toml_str(p) for p in proc_insts)
            print_valid_str = str(config.win_perf_counters.print_valid).lower()
            lines.extend([
                "# Read Windows Performance Counters (Broadcom VCF Operations template)",
                "[[inputs.win_perf_counters]]",
                f"  PrintValid = {print_valid_str}",
                "",
                "  [[inputs.win_perf_counters.object]]",
                '    ObjectName = "Processor"',
                '    Instances = ["*"]',
                '    Counters = ["% Idle Time", "% Interrupt Time", "% Privileged Time", "% Processor Time", "% User Time", "Interrupts/sec", "% DPC Time"]',
                '    Measurement = "win_cpu"',
                "    IncludeTotal = true",
                "",
                "  [[inputs.win_perf_counters.object]]",
                '    ObjectName = "LogicalDisk"',
                '    Instances = ["*"]',
                '    Counters = ["% Disk Read Time", "% Disk Write Time", "% Free Space", "% Idle Time", "Avg. Disk Bytes/Read", "Avg. Disk Bytes/Write", "Avg. Disk Queue Length", "Avg. Disk sec/Read", "Avg. Disk sec/Write", "Avg. Disk Write Queue Length", "Avg. Disk Read Queue Length", "Free Megabytes", "Split IO/Sec"]',
                '    Measurement = "win_disk"',
                "",
                "  [[inputs.win_perf_counters.object]]",
                '    ObjectName = "Memory"',
                '    Counters = ["Available Bytes", "Cache Bytes", "Committed Bytes", "Cache Faults/sec", "Demand Zero Faults/sec", "Page Faults/sec", "Pages/sec", "Transition Faults/sec", "Pool Nonpaged Bytes", "Pool Paged Bytes"]',
                '    Instances = ["------"]',
                '    Measurement = "win_mem"',
                "",
                "  [[inputs.win_perf_counters.object]]",
                '    ObjectName = "Network Interface"',
                '    Counters = ["Bytes Received/sec", "Bytes Sent/sec", "Packets Outbound Discarded", "Packets Outbound Errors", "Packets Received Discarded", "Packets Received Errors", "Packets Received/sec", "Packets Sent/sec", "Connections Established"]',
                '    Instances = ["*"]',
                '    Measurement = "win_net"',
                "    IncludeTotal = true",
                "",
                "  [[inputs.win_perf_counters.object]]",
                '    ObjectName = "Paging File"',
                '    Counters = ["% Usage"]',
                '    Instances = ["*"]',
                '    Measurement = "win_paging"',
                "    IncludeTotal = true",
                "",
                "  [[inputs.win_perf_counters.object]]",
                '    ObjectName = "Process"',
                '    Counters = ["% Privileged Time", "% Processor Time", "% User Time", "Elapsed Time", "Handle Count", "IO Read Bytes/sec", "IO Read Operations/sec", "IO Write Bytes/sec", "IO Write Operations/sec", "Private Bytes", "Thread Count", "Virtual Bytes", "Working Set", "Working Set - Private"]',
                f"    Instances = [{proc_insts_formatted}]",
                '    Measurement = "win_process"',
                "",
                "  [[inputs.win_perf_counters.object]]",
                '    ObjectName = "System"',
                '    Counters = ["Context Switches/sec", "Processes", "Processor Queue Length", "System Calls/sec", "System Up Time", "Threads"]',
                '    Instances = ["------"]',
                '    Measurement = "win_system"',
                "",
                "  [[inputs.win_perf_counters.object]]",
                '    ObjectName = "TCPv4"',
                '    Counters = ["Connection Failures", "Connections Active", "Connections Established", "Connections Passive", "Connection Reset", "Segments Received/sec", "Segments Retransmitted/sec", "Segments Sent/sec"]',
                '    Instances = ["------"]',
                '    Measurement = "win_net_tcp"',
                "",
                "  [[inputs.win_perf_counters.object]]",
                '    ObjectName = "TCPv6"',
                '    Counters = ["Connection Failures", "Connections Active", "Connections Established", "Connections Passive", "Connection Reset", "Segments Received/sec", "Segments Retransmitted/sec", "Segments Sent/sec"]',
                '    Instances = ["------"]',
                '    Measurement = "win_net_tcp"',
                "",
                "  [[inputs.win_perf_counters.object]]",
                '    ObjectName = "UDPv4"',
                '    Counters = ["Datagrams No Port/sec", "Datagrams Received/Errors", "Datagrams Received/sec", "Datagrams Sent/sec"]',
                '    Instances = ["------"]',
                '    Measurement = "win_net_udp"',
                "",
                "  [[inputs.win_perf_counters.object]]",
                '    ObjectName = "UDPv6"',
                '    Counters = ["Datagrams No Port/sec", "Datagrams Received/Errors", "Datagrams Received/sec", "Datagrams Sent/sec"]',
                '    Instances = ["------"]',
                '    Measurement = "win_net_udp"',
                "",
            ])

            if config.win_perf_counters.additional_objects:
                objects = tomllib.loads("\n".join(lines[perf_start:]))['inputs']['win_perf_counters'][0]['object']
                for extra in config.win_perf_counters.additional_objects:
                    existing = next((item for item in objects if item['ObjectName'] == extra.object_name), None)
                    if existing:
                        for key, additions in [('Counters', extra.counters), ('Instances', extra.instances)]:
                            combined = list(dict.fromkeys(existing[key] + additions))
                            existing[key] = ['*'] if '*' in combined else combined
                    else:
                        objects.append(dict(ObjectName=extra.object_name, Counters=extra.counters,
                                            Instances=extra.instances, Measurement=extra.measurement))
                lines[perf_start:] = ['[[inputs.win_perf_counters]]', f'  PrintValid = {print_valid_str}', '']
                for item in objects:
                    lines.append('  [[inputs.win_perf_counters.object]]')
                    for key, value in item.items():
                        if isinstance(value, list):
                            formatted = '[' + ', '.join(_escape_toml_str(v) for v in value) + ']'
                        elif isinstance(value, bool):
                            formatted = str(value).lower()
                        else:
                            formatted = _escape_toml_str(value)
                        lines.append(f'    {key} = {formatted}')
                    lines.append('')

        # Windows OS totals (same three inputs the Ops product-managed agent ships)
        if config.win_os.enabled:
            if config.win_os.cpu:
                lines.extend([
                    "# Windows CPU totals, prefixed to land on the Windows OS object in VCF Operations",
                    "[[inputs.cpu]]",
                    "  percpu = true",
                    "  totalcpu = true",
                    "  collect_cpu_time = true",
                    "  report_active = true",
                    '  name_prefix = "win."',
                    "",
                ])
            if config.win_os.mem:
                lines.extend(["# Windows memory totals", "[[inputs.mem]]", '  name_prefix = "win."', ""])
            if config.win_os.swap:
                lines.extend(["# Windows swap totals", "[[inputs.swap]]", '  name_prefix = "win."', ""])

        # Windows Services
        if config.win_services.enabled:
            lines.extend([
                "# Read Windows service states",
                "[[inputs.win_services]]",
            ])
            svc_list = ", ".join(_escape_toml_str(s) for s in config.win_services.service_names)
            lines.append(f"  service_names = [{svc_list}]")
            lines.append("")

        # NGINX
        if config.nginx.enabled:
            lines.extend([
                "# Read NGINX status metrics",
                "[[inputs.nginx]]",
            ])
            urls = ", ".join(_escape_toml_str(u) for u in config.nginx.urls)
            lines.append(f"  urls = [{urls}]")
            lines.append("")

        # Apache
        if config.apache.enabled:
            lines.extend([
                "# Read Apache server-status metrics",
                "[[inputs.apache]]",
            ])
            urls = ", ".join(_escape_toml_str(u) for u in config.apache.urls)
            lines.append(f"  urls = [{urls}]")
            lines.append("")

        # MySQL
        if config.mysql.enabled:
            lines.extend([
                "# Read MySQL / MariaDB server metrics",
                "[[inputs.mysql]]",
            ])
            servers = ", ".join(_escape_toml_str(s) for s in config.mysql.servers)
            lines.append(f"  servers = [{servers}]")
            lines.append("")

        # PostgreSQL
        if config.postgresql.enabled:
            lines.extend([
                "# Read PostgreSQL server metrics",
                "[[inputs.postgresql]]",
                f"  address = {_escape_toml_str(config.postgresql.address)}",
                "",
            ])

        # Microsoft SQL Server
        if config.mssql.enabled:
            lines.extend([
                "# Read Microsoft SQL Server metrics",
                "[[inputs.sqlserver]]",
            ])
            servers = ", ".join(_escape_toml_str(s) for s in config.mssql.servers)
            lines.append(f"  servers = [{servers}]")
            lines.append("")

        # Docker
        if config.docker.enabled:
            lines.extend([
                "# Read Docker container metrics",
                "[[inputs.docker]]",
                f"  endpoint = {_escape_toml_str(config.docker.endpoint)}",
                "",
            ])

        # Ping
        if config.ping.enabled:
            lines.extend([
                "# Read ping and reachability metrics",
                "[[inputs.ping]]",
            ])
            urls = ", ".join(_escape_toml_str(u) for u in config.ping.urls)
            lines.append(f"  urls = [{urls}]")
            lines.append(f"  count = {config.ping.count}")
            lines.append("")

        # Custom TOML Fragment
        if config.custom_toml and config.custom_toml.strip():
            lines.extend([
                "# Custom administrator TOML fragment",
                config.custom_toml.strip(),
                "",
            ])

        return "\n".join(lines).strip() + "\n"

    @staticmethod
    def render_vcf_output(
        collector_address: str,
        hostname: str,
        uuid: str = "",
        ip: str = "",
        verify_ssl: bool = True,
        ca_cert_path: Optional[str] = None,
        cert_path: Optional[str] = None,
        key_path: Optional[str] = None,
        vm_mor: Optional[str] = None,
        vc_id: Optional[str] = None,
        mandatory_tags_path: Optional[str] = None,
        telegraf_bin_path: Optional[str] = None,
        is_windows: bool = False,
        mutual_auth: bool = True,
    ) -> str:
        """Render the Broadcom VCF Operations Cloud Proxy Wavefront HTTP output.

        Conforms to Broadcom VCF Operations 9.1 open-source Telegraf sample configuration.
        Places output in telegraf.d/cloudproxy-http.conf.

        Args:
            collector_address: IP or FQDN of the Cloud Proxy.
            hostname: Target hostname.
            uuid: Host or VM UUID for unmanaged mapping.
            ip: Target IP address.
            verify_ssl: True if SSL certificate verification is enabled.
            ca_cert_path: Path to CA certificate bundle.
            cert_path: Path to client certificate.
            key_path: Path to client private key.
            vm_mor: Optional vCenter VM MOR if managed.
            vc_id: Optional vCenter Instance ID if managed.
            mandatory_tags_path: Optional path to mandatory_tags script.
            telegraf_bin_path: Optional path to telegraf binary.
            is_windows: True if target OS is Windows.
            mutual_auth: True if mutual TLS is enforced by Cloud Proxy.

        Returns:
            Formatted TOML string for telegraf.d/cloudproxy-http.conf.
        """
        # Clean hostname of any leading/trailing whitespace or newlines
        clean_hostname = hostname.strip().splitlines()[-1].strip() if hostname and hostname.strip() else "localhost"
        try:
            ipaddress.ip_address(clean_hostname)
            short_hostname = clean_hostname
        except ValueError:
            short_hostname = clean_hostname.split(".")[0]

        default_ca = "C:\\telegraf\\telegraf.d\\ca.pem" if is_windows else "/etc/telegraf/telegraf.d/ca.pem"
        default_cert = "C:\\telegraf\\telegraf.d\\cert.pem" if is_windows else "/etc/telegraf/telegraf.d/cert.pem"
        default_key = "C:\\telegraf\\telegraf.d\\key.pem" if is_windows else "/etc/telegraf/telegraf.d/key.pem"

        lines: List[str] = [
            MANAGED_HEADER,
            "# Global agent configuration for VCF Operations ingestion",
            "[agent]",
            '  interval = "300s"',
            "  round_interval = true",
            "  metric_batch_size = 1000",
            "  metric_buffer_limit = 2000",
            '  collection_jitter = "0s"',
            '  flush_interval = "60s"',
            '  flush_jitter = "0s"',
            '  precision = ""',
            "  debug = false",
            "  quiet = false",
            '  logfile = ""',
            f"  hostname = {_escape_toml_str(short_hostname)}",
            "  omit_hostname = true",
            "",
            "# Output configuration for VCF Operations Cloud Proxy",
            "[[outputs.http]]",
            f'  url = "https://{collector_address}/opensource/default/metric"',
            '  timeout = "5s"',
            '  method = "POST"',
            f"  insecure_skip_verify = {str(not verify_ssl).lower()}",
        ]

        if mutual_auth or (cert_path and key_path):
            actual_ca = ca_cert_path or default_ca
            actual_cert = cert_path or default_cert
            actual_key = key_path or default_key
            lines.append(f"  tls_ca = {_escape_toml_str(actual_ca)}")
            lines.append(f"  tls_cert = {_escape_toml_str(actual_cert)}")
            lines.append(f"  tls_key = {_escape_toml_str(actual_key)}")
            lines.append('  tls_min_version = "TLS13"')
        elif ca_cert_path:
            lines.append(f"  tls_ca = {_escape_toml_str(ca_cert_path)}")

        lines.extend([
            '  data_format = "wavefront"',
            "",
            "  [outputs.http.headers]",
            '    Content-Type = "text/plain; charset=utf-8"',
        ])

        if vm_mor and vc_id:
            lines.extend([
                f"    vmId = {_escape_toml_str(vm_mor)}",
                f"    vcid = {_escape_toml_str(vc_id)}",
                f"    hostname = {_escape_toml_str(short_hostname)}",
                '    uuid = ""',
            ])
        else:
            lines.extend([
                f"    uuid = {_escape_toml_str(uuid)}",
                f"    ip = {_escape_toml_str(ip)}",
                f"    hostname = {_escape_toml_str(short_hostname)}",
            ])

        if mandatory_tags_path:
            if is_windows:
                # Always quote both paths: Telegraf splits the command on spaces, and an unquoted
                # path under C:\Program Files runs C:\Program and the Guest Info tags never arrive.
                cmd_pfx = "cmd.exe /c"
                norm_script = mandatory_tags_path.replace("\\", "/")
                norm_bin = (telegraf_bin_path or "C:/telegraf/telegraf.exe").replace("\\", "/")
                cmd_str = f'{cmd_pfx} "{norm_script}" "{norm_bin}"'
            else:
                cmd_pfx = "/bin/bash"
                bin_path = telegraf_bin_path or "/usr/bin/telegraf"
                cmd_str = f'{cmd_pfx} "{mandatory_tags_path}" "{bin_path}"'
            lines.extend([
                "",
                "# Mandatory tag telemetry required for VCF Operations agent status",
                "[[inputs.exec]]",
                f"  commands = [{_escape_toml_str(cmd_str)}]",
                '  timeout = "5s"',
                '  data_format = "influx"',
            ])

        lines.append("")
        return "\n".join(lines).strip() + "\n"

    @staticmethod
    def render_base_stub() -> str:
        """Render a clean minimal base telegraf.conf stub without active inputs.

        Prevents duplicate metric collection alongside telegraf.d fragments.
        """
        lines = [
            MANAGED_HEADER,
            "# Base Telegraf agent configuration stub",
            "# Default inputs have been disabled to prevent duplicate metric collection.",
            "# All active input and output plugins are configured in telegraf.d/",
            "[agent]",
            '  interval = "300s"',
            "  round_interval = true",
            "  metric_batch_size = 1000",
            "  metric_buffer_limit = 10000",
            '  collection_jitter = "0s"',
            '  flush_interval = "60s"',
            '  flush_jitter = "0s"',
            '  precision = ""',
            "  debug = false",
            "  quiet = false",
            '  logfile = ""',
            "  omit_hostname = true",
            "",
        ]
        return "\n".join(lines).strip() + "\n"
